#!/usr/bin/env node
/**
 * Copy lip-synced avatar clips into the Remotion public dir and regenerate the
 * manifest the composition reads.
 *
 * Clips are looked up through a manifest rather than probed at render time
 * because a Remotion component runs in the browser and cannot stat the disk.
 * An unregistered clip is silently ignored, which is exactly the failure this
 * script exists to prevent — run it after every avatar batch.
 *
 *   node scripts/sync-avatar.mjs
 */
import {cpSync, existsSync, mkdirSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', '..', 'avatar');
const dest = join(here, '..', 'public', 'avatar');
const manifest = join(here, '..', 'src', 'avatarManifest.json');

mkdirSync(dest, {recursive: true});

const clips = {};
if (existsSync(src)) {
  for (const f of readdirSync(src)) {
    const m = f.match(/^(S\d+B?)\.(mp4|webm|mov)$/);
    if (!m) continue;
    cpSync(join(src, f), join(dest, f));
    clips[m[1]] = f;
  }
}

writeFileSync(
  manifest,
  JSON.stringify(
    {
      note:
        'Generated by scripts/sync-avatar.mjs. Maps scene id -> file under ' +
        'remotion/public/avatar/. Empty means every avatar beat falls back to ' +
        'the designed plate.',
      clips,
    },
    null,
    2
  ) + '\n'
);

const n = Object.keys(clips).length;
console.log(
  n === 0
    ? 'no avatar clips found — every avatar beat will render the designed plate'
    : `registered ${n} clip(s): ${Object.keys(clips).sort().join(', ')}`
);
